import type { NextPage } from 'next'
import Head from 'next/head'
import TodoApp from './../components/TodoApp'

const Home: NextPage = () => {

  return (
    <div className="bg-background min-h-screen flex">
      <Head>
        <title>Todo App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-full mt-3'>
        <TodoApp />
      </div>
    </div>
  )
}

export default Home